# Generated by Django 5.0.1 on 2024-03-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_player_height_alter_player_kg_and_more'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.RemoveField(
            model_name='team',
            name='trainers',
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to='accounts.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='trainers',
            field=models.ManyToManyField(to='accounts.trainer'),
        ),
    ]
