# Generated by Django 5.0.1 on 2024-03-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_team_players_remove_team_trainers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='count_limit',
            new_name='players_limit',
        ),
        migrations.AddField(
            model_name='team',
            name='trainers_limit',
            field=models.IntegerField(default=5, verbose_name='Quantidade maxima de Treinadores'),
            preserve_default=False,
        ),
    ]
