# Generated by Django 5.0.1 on 2024-01-12 01:03

import django.db.models.deletion
import django.utils.timezone
import sport.apps.accounts.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile', models.ImageField(blank=True, default='profile/not_img.jpg', null=True, upload_to='profile/', verbose_name='Foto de Perfil')),
                ('email', models.EmailField(error_messages={'unique': 'Email já Cadastrado!'}, max_length=150, unique=True, verbose_name='Email')),
                ('phone', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número de Telefone')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Ultimo Nome')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', sport.apps.accounts.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.FloatField(verbose_name='KG')),
                ('height', models.FloatField(verbose_name='Altura')),
                ('sex', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1, verbose_name='Sexo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1, verbose_name='Sexo')),
                ('year_exp', models.IntegerField(verbose_name='Anos de Experiencia')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
