# Generated by Django 5.0.1 on 2024-03-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='player',
            name='kg',
            field=models.FloatField(blank=True, null=True, verbose_name='KG'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='profile/not_img.jpg', null=True, upload_to='media/profile/', verbose_name='Foto de Perfil'),
        ),
    ]
